# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c12be453666f64c3fc70763faf06eb195fb1456cf0308ad5c656be65246d57ba6d6516abd79ef8b1dc727b8459fc9848e7c7d6a937dbbcf584fc28c541d1ef8e

test:
  secret_key_base: a506895530f190bb0e8e717739693391b839250fea2b40606e483d362ac2d910dee4f4a787ef7812342bf380c264907132ac38797de58f7c5a57b386e0f37e5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
